/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora_sisa;

import java.awt.Color;

/**
 *
 * @author ESTUDIANTE
 */
public class Main extends javax.swing.JFrame {
    String guardar;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        entrada1 = new javax.swing.JTextField();
        entrada2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sumar = new javax.swing.JButton();
        restar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        cambiarColor = new javax.swing.JButton();
        salida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        guardarResultado = new javax.swing.JButton();
        guardaM = new javax.swing.JButton();
        ponerM = new javax.swing.JButton();
        borrarM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entrada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrada1ActionPerformed(evt);
            }
        });
        jPanel1.add(entrada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 250, -1));
        jPanel1.add(entrada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 250, -1));

        jLabel1.setText("Ingrese el numero 1: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setText("Ingrese el numero 2:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        sumar.setText("+");
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });
        jPanel1.add(sumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        restar.setText("-");
        restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarActionPerformed(evt);
            }
        });
        jPanel1.add(restar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        limpiar.setText("AC");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 120, -1));

        cambiarColor.setText("Cambiar Colores");
        cambiarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarColorActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 120, 20));

        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        jPanel1.add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 350, -1));

        jLabel3.setText("Salida:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        guardarResultado.setText("ANS");
        guardarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 60, 30));

        guardaM.setText("M+");
        guardaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardaMActionPerformed(evt);
            }
        });
        jPanel1.add(guardaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 60, -1));

        ponerM.setText("MR");
        ponerM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerMActionPerformed(evt);
            }
        });
        jPanel1.add(ponerM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 60, -1));

        borrarM.setText("MC");
        borrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarMActionPerformed(evt);
            }
        });
        jPanel1.add(borrarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        // TODO add your handling code here:
        int a;
        int b;
        int suma;
        a = Integer.parseInt(entrada1.getText());
        b = Integer.parseInt(entrada2.getText());
        suma = a + b;
        salida.setText(String.valueOf(suma));
        
    }//GEN-LAST:event_sumarActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salidaActionPerformed

    private void entrada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrada1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrada1ActionPerformed

    private void restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarActionPerformed
        // TODO add your handling code here:
        int a;
        int b;
        int suma;
        a = Integer.parseInt(entrada1.getText());
        b = Integer.parseInt(entrada2.getText());
        suma = a - b;
        salida.setText(String.valueOf(suma));
    }//GEN-LAST:event_restarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        entrada1.setText("");
        entrada2.setText("");
        salida.setText("");
        restar.setBackground(Color.white);
        sumar.setBackground(Color.white);
        limpiar.setBackground(Color.white);
    }//GEN-LAST:event_limpiarActionPerformed

    private void cambiarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarColorActionPerformed
        // TODO add your handling code here:
        restar.setBackground(Color.CYAN);
        sumar.setBackground(Color.CYAN);
        limpiar.setBackground(Color.CYAN);
    }//GEN-LAST:event_cambiarColorActionPerformed

    private void guardarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarResultadoActionPerformed
        // TODO add your handling code here:
        String aux = salida.getText();
        entrada1.setText(aux);
        entrada2.setText("");
        salida.setText("");
        
    }//GEN-LAST:event_guardarResultadoActionPerformed

    private void guardaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardaMActionPerformed
        // TODO add your handling code here:
        guardar = entrada1.getText();
    }//GEN-LAST:event_guardaMActionPerformed
    
    private void ponerMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerMActionPerformed
        // TODO add your handling code here:
        entrada1.setText(guardar);
    }//GEN-LAST:event_ponerMActionPerformed

    private void borrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarMActionPerformed
        // TODO add your handling code here:
        guardar = "";
        borrarM.setBackground(Color.black);
    }//GEN-LAST:event_borrarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarM;
    private javax.swing.JButton cambiarColor;
    private javax.swing.JTextField entrada1;
    private javax.swing.JTextField entrada2;
    private javax.swing.JButton guardaM;
    private javax.swing.JButton guardarResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton ponerM;
    private javax.swing.JButton restar;
    private javax.swing.JTextField salida;
    private javax.swing.JButton sumar;
    // End of variables declaration//GEN-END:variables
}
